version: '3.7'
services:
    postgres:
        image: postgres:13.2
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5433:5432'
        volumes: 
          - ./postgres_public_posts.sql:/docker-entrypoint-initdb.d/create_tables.sql